PRODUCT_VERSION_MAJOR = 1
PRODUCT_VERSION_MINOR = 6

RISING_FLAVOR := Tiramisu
RISING_VERSION := 1.6
RISING_CODENAME := Hayabusa
RISING_RELEASE_TYPE := FINAL
RISING_CODE := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)

CURRENT_DEVICE=$(shell echo "$(TARGET_PRODUCT)" | cut -d'_' -f 2,3)
RISING_BUILDTYPE := COMMUNITY
LINEAGE_BUILD_DATE := $(shell date -u +%Y%m%d-%H%M)

ifeq ($(WITH_GMS), true)
	ifeq ($(TARGET_CORE_GMS), true)
    	RISING_PACKAGE_TYPE ?= CORE
	else 
    	RISING_PACKAGE_TYPE ?= GAPPS
	endif
else
    RISING_PACKAGE_TYPE ?= VANILLA
endif

# Internal version
LINEAGE_VERSION := risingOS-v$(RISING_VERSION)-$(RISING_CODENAME)-$(RISING_RELEASE_TYPE)-$(LINEAGE_BUILD_DATE)-$(CURRENT_DEVICE)-$(RISING_PACKAGE_TYPE)-$(RISING_BUILDTYPE)

# Display version
LINEAGE_DISPLAY_VERSION := risingOS-v$(RISING_VERSION)-$(RISING_CODENAME)-$(RISING_RELEASE_TYPE)-$(CURRENT_DEVICE)-$(RISING_PACKAGE_TYPE)-$(RISING_BUILDTYPE)
